/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2206 from the
 * contents of fs.xs. Do not edit this file, edit fs.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "fs.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"
#include "const-c.inc"

#ifdef WIN32
  #define WINDOWS
#else
  #define LINUX
#endif

#include "ftrScanAPI.h"
#ifdef WINDOWS
  #include <windows.h>
#else
  #include <stdlib.h>
  #include <string.h>
  #include <stdio.h>
  #include <ctype.h>
  #include <assert.h>
  #include <malloc.h>
  #define WIN32_LEAN_AND_MEAN
  #include <wine/windows/windows.h>
#endif

int imagebuffersize = 1048576;

unsigned char globalimage[1048576];
unsigned char globaltempimage[1048576];

FTRHANDLE hDevice;
FTRSCAN_IMAGE_SIZE ImageSize;

void rotate_and_invert (unsigned char * original, unsigned char * new,int width, int height)
{
	int x,y;
	int bx, by;

	for (by=0; by<height; by+=8)
	for (bx=0; bx<width; bx+=8)
	for (y=0; y<8; y++)
	for (x=0; x<8; x++)
	*(new + (width * (by + y)) + (bx + x)) = ~*(original + ((height * width) - (width * (by + y) - bx - x)));
}

int convert_to_bitmap(unsigned char * image, unsigned char * bitmapimage, BITMAPINFO * Info,unsigned char * tempimage)
{
	BITMAPFILEHEADER header;
	int i;
	unsigned int basesize;
	
	header.bfOffBits = 1078;
	header.bfReserved1 = 0;
	header.bfReserved2 = 0;
	header.bfSize = 1078 + ImageSize.nImageSize;
	header.bfType = (unsigned short)(('M'<<8) | 'B');
	
	for(i=0;i<256;i++)
	{
		Info->bmiColors[i].rgbBlue = i;
		Info->bmiColors[i].rgbRed = i;
		Info->bmiColors[i].rgbGreen = i;
		Info->bmiColors[i].rgbReserved = 0;
	}
	Info->bmiHeader.biBitCount = 8;
	Info->bmiHeader.biClrImportant = 0;
	Info->bmiHeader.biClrUsed = 0;
	Info->bmiHeader.biCompression = 0;
	Info->bmiHeader.biHeight = ImageSize.nHeight;
	Info->bmiHeader.biPlanes = 1;
	Info->bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
	Info->bmiHeader.biSizeImage = ImageSize.nImageSize;
	Info->bmiHeader.biWidth = ImageSize.nWidth;
	Info->bmiHeader.biXPelsPerMeter = 0;
	Info->bmiHeader.biYPelsPerMeter = 0;
	
	rotate_and_invert(image,tempimage,ImageSize.nWidth,ImageSize.nHeight);
	
	memcpy((unsigned char *) bitmapimage,(unsigned char *) &header,14);
	memcpy((unsigned char *) bitmapimage + sizeof(header),(unsigned char *) Info,1064);
	memcpy((unsigned char *) bitmapimage + 1078,(unsigned char *) tempimage,ImageSize.nImageSize);
	
	return(14 + 1064 + ImageSize.nImageSize);
}


#line 99 "fs.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 151 "fs.c"

/* INCLUDE:  Including 'const-xs.inc' from 'fs.xs' */


XS(XS_fs_constant); /* prototype to pass -Wmissing-prototypes */
XS(XS_fs_constant)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "sv");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 4 "const-xs.inc"
#ifdef dXSTARG
	dXSTARG; /* Faster if we have it.  */
#else
	dTARGET;
#endif
	STRLEN		len;
        int		type;
	/* IV		iv;	Uncomment this if you need to return IVs */
	/* NV		nv;	Uncomment this if you need to return NVs */
	/* const char	*pv;	Uncomment this if you need to return PVs */
#line 180 "fs.c"
	SV *	sv = ST(0);
	const char *	s = SvPV(sv, len);
#line 18 "const-xs.inc"
	type = constant(aTHX_ s, len);
      /* Return 1 or 2 items. First is error message, or undef if no error.
           Second, if present, is found value */
        switch (type) {
        case PERL_constant_NOTFOUND:
          sv =
	    sv_2mortal(newSVpvf("%s is not a valid IB::Extractor macro", s));
          PUSHs(sv);
          break;
        case PERL_constant_NOTDEF:
          sv = sv_2mortal(newSVpvf(
	    "Your vendor has not defined IB::Extractor macro %s, used",
				   s));
          PUSHs(sv);
          break;
	/* Uncomment this if you need to return IVs
        case PERL_constant_ISIV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHi(iv);
          break; */
	/* Uncomment this if you need to return NOs
        case PERL_constant_ISNO:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_no);
          break; */
	/* Uncomment this if you need to return NVs
        case PERL_constant_ISNV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHn(nv);
          break; */
	/* Uncomment this if you need to return PVs
        case PERL_constant_ISPV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, strlen(pv));
          break; */
	/* Uncomment this if you need to return PVNs
        case PERL_constant_ISPVN:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, iv);
          break; */
	/* Uncomment this if you need to return SVs
        case PERL_constant_ISSV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(sv);
          break; */
	/* Uncomment this if you need to return UNDEFs
        case PERL_constant_ISUNDEF:
          break; */
	/* Uncomment this if you need to return UVs
        case PERL_constant_ISUV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHu((UV)iv);
          break; */
	/* Uncomment this if you need to return YESs
        case PERL_constant_ISYES:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_yes);
          break; */
        default:
          sv = sv_2mortal(newSVpvf(
	    "Unexpected return type %d while processing IB::Extractor macro %s, used",
               type, s));
          PUSHs(sv);
        }
#line 256 "fs.c"
	PUTBACK;
	return;
    }
}


/* INCLUDE: Returning to 'fs.xs' from 'const-xs.inc' */


XS(XS_fs_ftrScanOpenDevice); /* prototype to pass -Wmissing-prototypes */
XS(XS_fs_ftrScanOpenDevice)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 97 "fs.xs"
		int ret;
#line 279 "fs.c"
	int	RETVAL;
	dXSTARG;
#line 99 "fs.xs"
		hDevice = ftrScanOpenDevice();
		if(hDevice == NULL) { ret = 1; }
		else { ret = 0; }
		if(ret == 0) { ftrScanGetImageSize(hDevice,&ImageSize); }
		RETVAL = ret;
#line 288 "fs.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_fs_ftrScanCloseDevice); /* prototype to pass -Wmissing-prototypes */
XS(XS_fs_ftrScanCloseDevice)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 111 "fs.xs"
		ftrScanCloseDevice(hDevice);
#line 310 "fs.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_fs_ftrScanSetDiodesStatus); /* prototype to pass -Wmissing-prototypes */
XS(XS_fs_ftrScanSetDiodesStatus)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "green, red");
    {
#line 119 "fs.xs"
		int ret;
#line 330 "fs.c"
	int	RETVAL;
	dXSTARG;
	int	green = (int)SvIV(ST(0));
	int	red = (int)SvIV(ST(1));
#line 121 "fs.xs"
		ret = ftrScanSetDiodesStatus(hDevice,green,red);
		RETVAL = ret;
#line 338 "fs.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_fs_ftrScanGetSerialNumber); /* prototype to pass -Wmissing-prototypes */
XS(XS_fs_ftrScanGetSerialNumber)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 130 "fs.xs"
		int ret;
		char * serialnum;
#line 359 "fs.c"
	SV *	RETVAL;
#line 133 "fs.xs"
		Newxz(serialnum,9,void);
		if(serialnum == NULL) { XSRETURN_UNDEF; }
		ret = ftrScanGetSerialNumber(hDevice,serialnum);
		if(ret != 1) { XSRETURN_UNDEF; }
 		RETVAL = newSVpv(serialnum,0);
 		Safefree(serialnum);
#line 368 "fs.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_fs_ftrScanIsFingerPresent); /* prototype to pass -Wmissing-prototypes */
XS(XS_fs_ftrScanIsFingerPresent)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 146 "fs.xs"
		int ret;
#line 389 "fs.c"
	int	RETVAL;
	dXSTARG;
#line 148 "fs.xs"
		ret = ftrScanIsFingerPresent(hDevice,NULL);
		RETVAL = ret;
#line 395 "fs.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_fs_ftrScanSetOptions); /* prototype to pass -Wmissing-prototypes */
XS(XS_fs_ftrScanSetOptions)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "option");
    {
#line 157 "fs.xs"
		int ret;
#line 415 "fs.c"
	long	RETVAL;
	dXSTARG;
	long	option = (long)SvIV(ST(0));
#line 159 "fs.xs"
		ret = ftrScanSetOptions(hDevice,option,option);
		if(ret == 0) { RETVAL = GetLastError(); }
		else { RETVAL = ret; }
#line 423 "fs.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_fs_ftrScanGetOptions); /* prototype to pass -Wmissing-prototypes */
XS(XS_fs_ftrScanGetOptions)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 169 "fs.xs"
		int ret;
		long options;
#line 444 "fs.c"
	long	RETVAL;
	dXSTARG;
#line 172 "fs.xs"
		ret = ftrScanGetOptions(hDevice,&options);
		if(ret == 0) { RETVAL = GetLastError(); }
		else { RETVAL = options; }
#line 451 "fs.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_fs_ftrScanGetFrame); /* prototype to pass -Wmissing-prototypes */
XS(XS_fs_ftrScanGetFrame)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 182 "fs.xs"
		int ret;
#line 471 "fs.c"
	int	RETVAL;
	dXSTARG;
#line 185 "fs.xs"
		ret = ftrScanGetFrame(hDevice,globaltempimage,NULL);
		if(ret != 1) { XSRETURN_UNDEF; }
		memcpy((unsigned char *) &globalimage,(unsigned char *) &globaltempimage,imagebuffersize);
		RETVAL = ret;
#line 479 "fs.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_fs_ftrScanGetBitmap); /* prototype to pass -Wmissing-prototypes */
XS(XS_fs_ftrScanGetBitmap)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 195 "fs.xs"
		unsigned char * bitmapimage;
		unsigned char * tempimage;
		BITMAPINFO * Info;
		int size;
#line 502 "fs.c"
	SV *	RETVAL;
#line 200 "fs.xs"
		Newxz(bitmapimage,1048576,unsigned char);
		Newxz(tempimage,1048576,unsigned char);
		Newxz(Info,1064,BITMAPINFO);

		size = convert_to_bitmap(globalimage,bitmapimage,Info,tempimage);
 		RETVAL = newSVpv(bitmapimage,size);
		Safefree(bitmapimage);
		Safefree(tempimage);
		Safefree(Info);
#line 514 "fs.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_fs_ftrScanGetImageSize); /* prototype to pass -Wmissing-prototypes */
XS(XS_fs_ftrScanGetImageSize)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 216 "fs.xs"
		EXTEND(SP, 3);
 		PUSHs(sv_2mortal(newSViv(ImageSize.nWidth)));
 		PUSHs(sv_2mortal(newSViv(ImageSize.nHeight)));
 		PUSHs(sv_2mortal(newSViv(ImageSize.nImageSize)));
#line 540 "fs.c"
	PUTBACK;
	return;
    }
}


XS(XS_fs_ftrScanStatusDevice); /* prototype to pass -Wmissing-prototypes */
XS(XS_fs_ftrScanStatusDevice)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 225 "fs.xs"
		int ret;
		FTRSCAN_INTERFACES_LIST InterfaceList;
		int mydevice;
#line 562 "fs.c"
	int	RETVAL;
	dXSTARG;
#line 229 "fs.xs"
		ret = ftrScanGetInterfaces(&InterfaceList);
		mydevice = ftrGetBaseInterfaceNumber();
		RETVAL = !(InterfaceList.InterfaceStatus[mydevice]);
#line 569 "fs.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_fs); /* prototype to pass -Wmissing-prototypes */
XS(boot_fs)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("fs::constant", XS_fs_constant, file);
        newXS("fs::ftrScanOpenDevice", XS_fs_ftrScanOpenDevice, file);
        newXS("fs::ftrScanCloseDevice", XS_fs_ftrScanCloseDevice, file);
        newXS("fs::ftrScanSetDiodesStatus", XS_fs_ftrScanSetDiodesStatus, file);
        newXS("fs::ftrScanGetSerialNumber", XS_fs_ftrScanGetSerialNumber, file);
        newXS("fs::ftrScanIsFingerPresent", XS_fs_ftrScanIsFingerPresent, file);
        newXS("fs::ftrScanSetOptions", XS_fs_ftrScanSetOptions, file);
        newXS("fs::ftrScanGetOptions", XS_fs_ftrScanGetOptions, file);
        newXS("fs::ftrScanGetFrame", XS_fs_ftrScanGetFrame, file);
        newXS("fs::ftrScanGetBitmap", XS_fs_ftrScanGetBitmap, file);
        newXS("fs::ftrScanGetImageSize", XS_fs_ftrScanGetImageSize, file);
        newXS("fs::ftrScanStatusDevice", XS_fs_ftrScanStatusDevice, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

